first commit
MateAcademy-FE-study/law_agency pull request #4
Opened 2018-08-10 21:06 UTC by OksanaCoder

2018-08-11 09:38 UTC, Petrushchenko reviewed
.wrapper should be one for all sections

2018-08-14 06:44 UTC, tatsiak requested changes

2018-08-14 06:44 UTC, tatsiak commented on src/index.html
> +     <div class="wrapper">
wrapper should be common for all sections

2018-08-14 06:44 UTC, tatsiak commented on src/style/_news.scss
> +		margin-left: -3px;
all styles for &__right should be declared at one place

2018-08-14 15:29 UTC, tatsiak approved these changes

2018-08-14 15:29 UTC, merged